name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libglfw3-dev libgl1-mesa-dev pkg-config

    - name: Configure with CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_CONFIGURATION}} -j$(nproc)
